#! /bin/bash

count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "scenario_4 -- 1 sender -- test $count"
  echo "==========================================="
  date
  seconds
  iperf3 -c 10.10.10.1 -p 5801 -t 60
  count=$(( $count + 1 ))
  sleep 3
done

count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "scenario_4 -- 10 senders -- test $count"
  echo "==========================================="
  date
  seconds
  iperf3 -c 10.10.10.1 -p 5801 -t 60 -P 10
  count=$(( $count + 1 ))
  sleep 3
done

