#! /bin/bash

PROTON_DIR=/home/mick/latest/qpid-proton-0.35.0
INSTALL_DIR=/home/mick/latest/install/proton


for client in direct recv send 
do
  echo " "
  echo "   compile ${client}..."
  /usr/bin/cc  -I${PROTON_DIR}/c/include \
               -I${PROTON_DIR}/c/src     \
               -I${PROTON_DIR}/build/c/include \
               -I${PROTON_DIR}/build/c/src \
               -fvisibility=hidden -O2 -g \
               -DNDEBUG -std=c99 -MD -MT  \
               ./${client}.c.o -MF ./${client}.c.o.d \
               -o ./${client}.c.o \
               -c ./${client}.c

  echo "   link ${client}"
  /usr/bin/cc  -fvisibility=hidden -O2 -g \
               -DNDEBUG -rdynamic         \
               ./${client}.c.o -o ${client}  \
               -Wl,-rpath,${PROTON_DIR}/build/c \
               ${INSTALL_DIR}/lib64/libqpid-proton-proactor.so.1.8.1 \
               ${INSTALL_DIR}/lib64/libqpid-proton-core.so.10.12.0 \
               -lpthread
done

echo " "
echo "Copying executables..."
echo " "
cp ./send   ../scenario_1/amqp/CG
cp ./direct ../scenario_1/amqp/Br

cp ./send   ../scenario_2/amqp/CG
cp ./recv   ../scenario_2/amqp/Br

cp ./send   ../scenario_3/amqp/CG
cp ./recv   ../scenario_3/amqp/Br

