#! /bin/bash



count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "TEST $count"
  echo "==========================================="
  ./direct 10.10.10.1  5678
  sleep 1
  count=$(( $count + 1 ))
done

