#! /bin/bash

count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "scenario_5 -- 1 sender -- test $count"
  echo "==========================================="
  date
  seconds
  iperf3 -c 192.168.1.125 -p 5801 -t 60
  count=$(( $count + 1 ))
done


count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "scenario_5 -- 10 senders -- test $count"
  echo "==========================================="
  date
  seconds
  iperf3 -c 192.168.1.125 -p 5801 -t 60 -P 10
  count=$(( $count + 1 ))
done

