#! /bin/bash



count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "TEST $count"
  echo "==========================================="
  ./recv 10.10.10.1  5800   addr
  sleep 1
  count=$(( $count + 1 ))
done

