#! /bin/bash


CONCURRENT=1
count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "scenario_1 -- 1 sender -- test $count"
  echo "==========================================="
  count=$(( $count + 1 ))
  hey -cpus 16 -c ${CONCURRENT}  -z 60s http://10.10.10.1:80/index.html
done


CONCURRENT=10
count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "scenario_1 -- 10 senders -- test $count"
  echo "==========================================="
  count=$(( $count + 1 ))
  hey -cpus 16 -c ${CONCURRENT}  -z 60s http://10.10.10.1:80/index.html
done





