#! /bin/bash

count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "TEST $count"
  echo "==========================================="
  ./send 10.10.10.1 5800
  sleep 3
  count=$(( $count + 1 ))
done

