#! /bin/bash

BUOYANT=/home/mick/strest-grpc/release/linux/strest-grpc


CONCURRENT=1
count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "scenario_3 -- 1 sender -- test $count"
  echo "==========================================="
  count=$(( $count + 1 ))
  ${BUOYANT} client  --latencyUnit us --connections 1 --iterations 6 --address 10.10.10.2:5800
done


CONCURRENT=10
count=1
while [ $count -lt 6 ]
do
  echo "==========================================="
  echo "scenario_3 -- 10 senders -- test $count"
  echo "==========================================="
  count=$(( $count + 1 ))
  ${BUOYANT} client  --latencyUnit us --connections 10 --iterations 6 --address 10.10.10.2:5800
done


